### ISSUE TITLE
'Issue templates' and 'Pull request template' in awesome-electron-alternatives?

### ISSUE THREAD

**Issue by nichdemos** [sudhakar3697/awesome-electron-alternatives#71]
Hi @sudhakar3697, how are you?

What an incredible project! 

I noticed something interesting, there is a feature on GitHub called 'Issue templates' and 'Pull request Templates', this allows you to automate the process of opening and closing issues, pull-requests. **Read more** [About issue and pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)

Please see this: PR: [add 'Issue Template' and 'Pull request template' in awesome-electron-alternatives](https://github.com/sudhakar3697/awesome-electron-alternatives/pull/72)

***img-before*** |  ***img-after***
:-------------------------:|:-------------------------:
![image](https://github.com/sudhakar3697/awesome-electron-alternatives/assets/154566915/e9c34487-6bd9-4fbb-876f-9a2d7ca14856) | ![image](https://github.com/sudhakar3697/awesome-electron-alternatives/assets/154566915/bd53fe3b-2178-4fb1-88e3-672183c4ec6d)

***Have you all ever thought about adding the Issue templates' and 'Pull request Templates' feature here to automate the process of opening and closing issues, pull-requests?***

**Comment by sudhakar3697** [comment]
Hi @nichdemos,

Thanks for the effort, but this repo is just an informative repo. I do not think these templates would make sense for this repo containing just a markdown file.

Thank you.
