### ISSUE TITLE
can I share this project with my developer friends?

### ISSUE THREAD

**Issue by nichdemos** [sudhakar3697/awesome-electron-alternatives#74]
Hi @sudhakar3697, how are you?

Can I share this project with my developer friends?  Is there any image or trademark rights in this open source project that restrict the dissemination and promotion of this project?

**Comment by sudhakar3697** [comment]
Hi @nichdemos,

I am good, hoping you are doing well. Sure, no problem at all.

**Comment by nichdemos** [comment]
Hi @sudhakar3697, thanks!
