### ISSUE TITLE
Great repo

### ISSUE THREAD

**Issue by nuttyartist** [sudhakar3697/awesome-electron-alternatives#81]
Anyone knows if there's a repo for awesome cross-platform apps that aren't web based (e.g., Qt, GTK, Flutter, native, etc)?

**Comment by wesamdev** [comment]
if you wana make great gui apps without web based use QT its modern allow you to code styles in css ans its supports python and c++ and more.

**Comment by lucasnuic** [comment]
why don't we create an  awesome-cross-platform-apps-that-aren't-web-based project for this?

**Comment by sudhakar3697** [comment]
I guess there are non-web-based alternatives also listed here. Right?

**Comment by nuttyartist** [comment]
> I guess there are non-web-based alternatives also listed here. Right?

This repo is for frameworks, it will be cool to have one for applications that are cross-platform but not web based.

**Comment by lucasnuic** [comment]
> This repo is for frameworks, it will be cool to have one for applications that are cross-platform but not web based.

I think it makes sense what you're saying and requesting here

**Comment by arjunmenon** [comment]
Check out [Sciter](https://sciter.com/)

**Comment by lucasnuic** [comment]
Guys, please follow my project: [awesome-strategies-crossplataform-apps](https://github.com/lucasnuic/awesome-strategies-crossplataform-apps). Here I describe how to make crossplatform apps the right way.  I'm writing about cross-platform creation strategies.  Maybe this contributes a lot here.

**Comment by wesamdev** [comment]
@sudhakar3697 Close issue
